### ISSUE TITLE
The problem with the wrong choice

### ISSUE THREAD

**Issue by Quantum-of-Blackness** [IIInitiationnn/BloodEmporium#11]
In the last steps, the program tries to select an unavailable node

[debug-22-12-04 14-06-09.log](https://github.com/IIInitiationnn/BloodEmporium/files/10148314/debug-22-12-04.14-06-09.log)
[debug-22-12-04 13-59-45.log](https://github.com/IIInitiationnn/BloodEmporium/files/10148315/debug-22-12-04.13-59-45.log)

**Comment by IIInitiationnn** [comment]
This is a known issue with the current background, and I will attempt to resolve it in the coming weeks. Thanks for reporting the bug as always. Will update this issue when resolved.

**Comment by Quantum-of-Blackness** [comment]
At some point an error occurred
[debug-22-12-07 00-28-45.log](https://github.com/IIInitiationnn/BloodEmporium/files/10170510/debug-22-12-07.00-28-45.log)

**Comment by IIInitiationnn** [comment]
This issue has been resolved in the new 1.0.0 update.
