### ISSUE TITLE
error when running the program with the Epic Games Store version of DBD

### ISSUE THREAD

**Issue by jchillP** [IIInitiationnn/BloodEmporium#14]
i got this error

initialisation, merging
capturing screen
matched origin: origin_basic_black.png
vector: circles and match to unlockables
Traceback (most recent call last):
  File "state.py", line 143, in run
  File "matcher.py", line 78, in vector_circles
  File "matcher.py", line 98, in get_circle_properties
cv2.error: OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-q3d_8t8e\opencv\modules\imgproc\src\hough.cpp:2253: error: (-215:Assertion failed) !_image.empty() && _image.type() == CV_8UC1 && (_image.isMat() || _image.isUMat()) in function 'cv::HoughCircles'

i don't what what this means, so i tried running as admin, downloading the default icons from DBDtoolbox , my resolution is 1440x900.

**Comment by IIInitiationnn** [comment]
At the moment only 16:9 and widescreen resolutions are supported. Support for all resolutions will be coming in an update soon. In the meantime you will probably need to change the resolution of the game or monitor to use the app. Sorry for the inconvenience!

**Comment by jchillP** [comment]
yea, it works perfectly after i changed the res, i can tolerate a few clicks to save tens of thousands of clicks, thank you!
