### ISSUE TITLE
Bloodweb Node Traversal Lacks Awareness of Existing BP

### ISSUE THREAD

**Issue by theczorn** [IIInitiationnn/BloodEmporium#15]
**Location**: On any given bloodweb.
**Description**: Attempting run BP Emporium when your Bloodpoint total is low (e.g. - 1000 BP) causes the node traversal to blindly attempt to navigate the bloodweb even though you don't actually have enough points to purchase any given node.

As a QoL improvement, OCR on the users existing blood point total could be factored into existing logic, so that:
a. Execution halts when we no longer have a viable amount of BP to consume
b. Execution halts when we hit our Prestige/BP cap

Whichever comes first.

**Comment by IIInitiationnn** [comment]
Great suggestion, will look into incorporating into a future update.

**Comment by IIInitiationnn** [comment]
Implemented as of version 1.1.0!
