### ISSUE TITLE
Settings to allow alternate mouse buttons

### ISSUE THREAD

**Issue by theczorn** [IIInitiationnn/BloodEmporium#16]
Location: Any Bloodweb

Steps (Windows 11):
1. Navigate to Start Menu
2. Search for "mouse"
3. Select "Mouse Settings" option
4. Change Primary Mouse button from "Left" to "Right"
5. Run BPE against any bloodweb

Expected: BPE traverses nodes and buys things BAU.
Actual: BPE traverses nodes, clicking with the "Left" button by default. Due to binding alterations this is technically a "Right-Click" and doesn't purchase the target node. Traversal continues as expected, just without actual progression.

**Comment by IIInitiationnn** [comment]
Hi, sorry for the delay. I am adding a setting to configure this in the upcoming update!

**Comment by IIInitiationnn** [comment]
Change has been implemented in the latest v1.0.0-alpha.4 version. Full release will also contain the feature, I've tested it and it seems to be working fine, so I will mark this feature request as completed for now, but if you run into any issues, please do not hesitate to reopen this thread!
