### ISSUE TITLE
can you help? there is an error.

### ISSUE THREAD

**Issue by 08734271** [IIInitiationnn/BloodEmporium#17]
hello. thank you for ur efforts -this program. always good to use.
a error occurred this time n the program cannot be run....

attach log(
[debug-22-12-30 13-22-20.log](https://github.com/IIInitiationnn/BloodEmporium/files/10323107/debug-22-12-30.13-22-20.log)
) 
my 2 million BP are waiting for your help...!!!!!! 
(_ _) thank you as always.. u a my -or mag's- savior. >: )

**Comment by IIInitiationnn** [comment]
Is this isolated to a particular bloodweb, or is it happening across multiple characters? If this program works on many bloodwebs but fails on one particular character, it may be isolated to incorrect detection on that bloodweb.

If the program is not working across all characters, please use the following checklist.
1. Correctly set your resolution and UI scale.
2. If you are using a custom icon pack, set your path to the correct installation folder (if you have an installation which is not at the default location).
3. Ensure the path to Blood Emporium.exe does not contain any special unicode characters - e.g. some users had Russian and Chinese characters in a parent folder of the executable, causing it to bug out - see https://github.com/IIInitiationnn/BloodEmporium/issues/5.
4. Disable any shaders / visual filters.
5. Try swapping your game onto your primary monitor (if you have multiple).

**Comment by SubtleMetaphor** [comment]
I'm having the same issue. Used to be able to run blood emporium just fine, but doesn't work anymore.

I did upgrade my screen to 1440p recently, and I have configured this resolution in blood emporium, and yet it doesn't seem to work.

Any ideas?

[debug-23-01-03 08-20-55.log](https://github.com/IIInitiationnn/BloodEmporium/files/10334820/debug-23-01-03.08-20-55.log)

**Comment by IIInitiationnn** [comment]
Hi, sorry for the delay in responding.
Please use the checklist in the prior message. Make sure you press the save button in your settings (common mistake some people have missed, and I will probably add a warning when people click off without saving in future). If you are still having issues, please send a fullscreen screenshot of your game at the time you are running the app, as well as your `config.json` file.

**Comment by Mimonsi** [comment]
I just had the same issue. After changing resolution the issue still persisted, so I disabled my custom icon pack and returned to default icons, maybe this could help you too, if applicable.

**Comment by IIInitiationnn** [comment]
> I just had the same issue. After changing resolution the issue still persisted, so I disabled my custom icon pack and returned to default icons, maybe this could help you too, if applicable.

Would you be able to send any relevant log files? Would love to look at why this is happening, custom icons are supported by this app.

**Comment by Mimonsi** [comment]
I just reinstalled the custom icons and it is still working. Apparently my issue was me failing to set the correct resolution. I don't have any issues now, thank you.

**Comment by SubtleMetaphor** [comment]
> Hi, sorry for the delay in responding. Please use the checklist in the prior message. Make sure you press the save button in your settings (common mistake some people have missed, and I will probably add a warning when people click off without saving in future). If you are still having issues, please send a fullscreen screenshot of your game at the time you are running the app, as well as your `config.json` file.

![Untitled](https://user-images.githubusercontent.com/6630276/210765561-244cf261-5fe2-421d-8f02-6ce369759bc0.png)

[config.txt](https://github.com/IIInitiationnn/BloodEmporium/files/10351517/config.txt)

Couldn't upload json so changed filetype to txt.

**Comment by SubtleMetaphor** [comment]
Maybe it has something to do with the windows setting "Make everything bigger". Currently running it at 125% at 1440p.

**Comment by Mimonsi** [comment]
In case this might be useful, I attached a screensot of my game using 100% Windows UI Resolution. My ingame resolution is also at 100%, I don't notice a difference in our screenshots, I think "make everything bigger" has no impact here. Feel free to use my 1440p image to compare though. ![100percent](https://user-images.githubusercontent.com/24923925/211146314-f5f8d91f-b560-4bdf-9a4c-c3149dcd08be.png)

**Comment by IIInitiationnn** [comment]
Thanks for the additional information. I have tested on my system with both screenshots, and I was unable to reproduce the bug.

@SubtleMetaphor Would you be able to check if this is an issue across multiple characters' bloodwebs, or just isolated to that one bloodweb?

**Comment by SubtleMetaphor** [comment]
I changed my "Make everything bigger" to 100% and managed to get Blood Emporium to work, so as far as my case is concerned this seems to be the culprit.
