### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Kiwiiiiiiiiiiii** [IIInitiationnn/BloodEmporium#18]
Hello, pls help me. Idk what to do now. I opened log component and this what I faund.

initialisation, merging
Traceback (most recent call last):
  File "state.py", line 120, in run
  File "mergedbase.py", line 55, in __init__
  File "mergedbase.py", line 80, in __get_valid_images
AttributeError: 'NoneType' object has no attribute 'shape'

this saying ur app after I press "Run": An error occurred. Please check debug-23-01-07 16-17-42.log for additional details.

**Comment by IIInitiationnn** [comment]
It is highly likely you have special unicode characters in your path to `Blood Emporium.exe` (where you unzipped the application). Please see https://github.com/IIInitiationnn/BloodEmporium/issues/5 and if you still have issues, feel free to drop another reply.
