### ISSUE TITLE
Is this safe?

### ISSUE THREAD

**Issue by IAmCosmin-YT** [IIInitiationnn/BloodEmporium#2]

**Comment by IIInitiationnn** [comment]
In the sense of whether you will be banned for using it, it should be safe.
In the sense of whether it contains malware, you can check for yourself. Any assurances I provide hold no validity, as the sole developer of this project. But I think it should be fairly clear I have not bundled any malware in this.
If you have any other questions, please let me know :)

**Comment by IAmCosmin-YT** [comment]
> In the sense of whether you will be banned for using it, it should be safe. In the sense of whether it contains malware, you can check for yourself. Any assurances I provide hold no validity, as the sole developer of this project. But I think it should be fairly clear I have not bundled any malware in this. If you have any other questions, please let me know :)

Thanks
