### ISSUE TITLE
Not running properly

### ISSUE THREAD

**Issue by Laroque29** [IIInitiationnn/BloodEmporium#20]
Hi, thank you so much for making this. I can't stand the slow bloodweb.

My issue is: the program can sometimes do 1 or 2 perks but then can't do anymore (and mostly cant do any at all).

I'm borderline tech-illiterate but I did go through all the open and closed cases to see if there was a solution already so as not to waste anyone's time but I don't think I saw any.

Screenshots of bloodweb and my graphics settings:
![image](https://user-images.githubusercontent.com/46994702/212489691-355084fe-c22f-4320-85d9-4d1ffc6f0103.png)
![image](https://user-images.githubusercontent.com/46994702/212489707-c3959b79-fee7-4fa6-a1a3-878f00616ce6.png)

Most recent debug log:
[debug-23-01-14 18-20-00.log](https://github.com/IIInitiationnn/BloodEmporium/files/10418533/debug-23-01-14.18-20-00.log)

**Comment by IIInitiationnn** [comment]
Have you correctly saved your resolution and UI scale in your app settings? This error generally only occurs because the app is failing to detect your bloodweb.

**Comment by Laroque29** [comment]
Thank you again so much. It all works now!

I didn't know those settings where in the app and also I saw the app was routing to the wrong storage drive for the icons. 

Much obliged
