### ISSUE TITLE
crash middle run. please help 

### ISSUE THREAD

**Issue by siputturbo** [IIInitiationnn/BloodEmporium#22]
[debug-23-01-27 11-37-47.log](https://github.com/IIInitiationnn/BloodEmporium/files/10515307/debug-23-01-27.11-37-47.log)

**Comment by siputturbo** [comment]
i created a new profile and gave envelope + mystery box value 150 and didnt modify the rest but from the log file, it shows others are 9999 value. is that correct? thanks

**Comment by siputturbo** [comment]
cv2.error: OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-q3d_8t8e\opencv\modules\imgproc\src\hough.cpp:2253: error: (-215:Assertion failed) !_image.empty() && _image.type() == CV_8UC1 && (_image.isMat() || _image.isUMat()) in function 'cv::HoughCircles'

**Comment by IIInitiationnn** [comment]
Several questions about your issue:
1. Are you using the correct profile and character, and did you save your changes to the profile before use? When you created a new profile, did you initialise it from the blank profile? If so, all items will be equally selected, except for the mystery box change you made.
2. Is the mid-program termination a recurring issue or a one-time issue? You can test on other bloodwebs to verify.
3. Was there anything during the runtime that could have caused this issue e.g. screen being covered by another window, game minimised etc. (an extension of the above question - please check if this issue occurs in all bloodwebs)
