### ISSUE TITLE
Pop up message will interrupt the process

### ISSUE THREAD

**Issue by caxrlxos** [IIInitiationnn/BloodEmporium#23]
bloodemporium couldn't recognize message window popped up by a special event node (mystery box), and it will constantly try to select those nodes not connected yet.
![image](https://user-images.githubusercontent.com/13828762/216781734-775b40a7-0a8b-45e4-9245-b5b2c2831a52.png)

![image](https://user-images.githubusercontent.com/13828762/216781649-072f2dd7-61a5-4798-a107-6b41cecc6a41.png)

**Comment by IIInitiationnn** [comment]
Hey! This is a known issue which will probably not be resolved by the time the event is over. The app should resume working properly when regular mystery boxes are restored. Sorry for any inconvenience!
