### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by MarceloBrazolim** [IIInitiationnn/BloodEmporium#24]
initialisation, merging
capturing screen
matched origin: origin_basic_red.png
vector: circles and match to unlockables
hough transform: lines
creating networkx graph
NODES
    ORIGIN
EDGES
Traceback (most recent call last):
  File "state.py", line 186, in run
ValueError: max() arg is an empty sequence

i tried resetting to the original icon pack;
toyed with the profile system, including the default one;
checked the icon path in settings;
checked the game settings file for resolution and scale (all match);
executed the program as adm;
tried with both surv and killer, and
tried with limits and without.

only thing i didn't test changing is the language in the GameUserSettings.ini , which is Language=en (not sure if this is correct, i changed directly through the file and didn't have a problem since).

it's always the same log. i don't know what to test next at this point.

**Comment by IIInitiationnn** [comment]
This issue has been resolved in the new 1.0.0 update.
