### ISSUE TITLE
It gets partially through the bloodweb and then fails

### ISSUE THREAD

**Issue by SPLNTZ** [IIInitiationnn/BloodEmporium#25]
level cleared
capturing screen
matched origin: origin_basic_black.png
vector: circles and match to unlockables
hough transform: lines
creating networkx graph
NODES
    ORIGIN
    1_CLAIMED
    2_CLAIMED
    3_CLAIMED
    4_CLAIMED
    5_iconAddon_bloodAmber_survivor
EDGES
    ORIGIN    1_CLAIMED
    ORIGIN    3_CLAIMED
    ORIGIN    2_CLAIMED
    1_CLAIMED 2_CLAIMED
    3_CLAIMED 4_CLAIMED
pre-correction
optimiser
    updated nodes
        ORIGIN    value 9999       accessible True  claimed True
[debug-23-02-25 10-03-48.log](https://github.com/IIInitiationnn/BloodEmporium/files/10831940/debug-23-02-25.10-03-48.log)

        1_CLAIMED value 9999       accessible True  claimed True
        2_CLAIMED value 9999       accessible True  claimed True
        3_CLAIMED value 9999       accessible True  claimed True
        4_CLAIMED value 9999       accessible True  claimed True
        5_iconAddon_bloodAmber_survivor value 29997      accessible False claimed False
Traceback (most recent call last):
  File "state.py", line 214, in run
IndexError: list index out of range

**Comment by SPLNTZ** [comment]
Hey my man,

I think the programming just needs some "try again" features rather than just failing after 30 seconds.  I know some C# but not python ATM or I would try to correct this.  Keep up the good work.

**Comment by SPLNTZ** [comment]
Tested on another computer and it seems fine.  Ran through all the BP.  Strange

**Comment by IIInitiationnn** [comment]
We're working on changes to the program in time with the next major game update to address these issues. Thanks for letting us know about it.

**Comment by IIInitiationnn** [comment]
This issue has been resolved in the new 1.0.0 update.
