### ISSUE TITLE
Some issue with using custom UI packs.

### ISSUE THREAD

**Issue by YuiKio** [IIInitiationnn/BloodEmporium#27]
The program can be run in the default configuration,when you dont change UI path.
Log content below:
initialisation at 1920 x 1080 @ 100; merging
region: (256, 159) to (1108, 1011)
Traceback (most recent call last):
  File "state.py", line 153, in run
  File "mergedbase.py", line 55, in __init__
  File "mergedbase.py", line 86, in __get_valid_images
ValueError: operands could not be broadcast together with shapes (262,262) (256,256)

**Comment by YuiKio** [comment]
Using UI Pack:
perks:
dbdicontoolbox://PhantomXD-dead-by-daylight-Danganronpa-creator-of-AbsolutVodkaMain
dbdicontoolbox://MammothAdanv1-Dead-by-Daylight-Danganronpa-Roots-of-the-Dread
dbdicontoolbox://MammothAdanv1-MammothAdanv1-Dead-by-Daylight-Danganronpa-Project-W-(2)
dbdicontoolbox://MammothAdanv1-MammothAdanv1-Dead-by-Daylight-Danganronpa-Forged-in-the-Fog
other:
dbdicontoolbox://Fiend-+-WheatDraws-Hades-Pack
thats may help you.

**Comment by IIInitiationnn** [comment]
Icon files should only be 256x256 pixels, and should be RGB or RGBA. In this instance, it seems the author of your icon pack has some files which are not the correct dimensions (262x262). If you can correct those files (whether by removing, cropping, etc.), the program should be able to run.
