### ISSUE TITLE
Mouse click to get the Item/perk from bloodweb not working

### ISSUE THREAD

**Issue by mateusmcordeiro** [IIInitiationnn/BloodEmporium#28]
I've tried all the issues resolutions i found, but none of them solved my problem.

When i run, it finds the perks/items positions on bloodweb but  getting them is not working (mouse is moving automatic on a well way but doesnt trigger the mouse click)

What i've tring to do to fix it (but not working):
- Disable visual effects
- set UI scale and game hud to 70% and set this inside bloodempirium config
- set deadbydaylight config files to fix fullscreen mode (because default its fullscreen windowed)

Fun fact: "Bloodpoints spent" counter is counting all the items/perks its "tries to get", like if it worked but didnt.

**Comment by IIInitiationnn** [comment]
Which version of the program are you using? And also do you happen to have LMB and RMB swapped (a Windows 11 setting - unlikely to apply to you, but I figured I'd ask just in case).
In the meantime, I would see if it's possible to start running the app, then before it starts moving the mouse or making selections, see if you can click into your game to make sure your cursor is focused in DBD.

**Comment by mateusmcordeiro** [comment]
i tried the last stable release (0.3.2) and the three alpha one.

**Comment by mateusmcordeiro** [comment]
I swapped LMB/RMB (to test, but i use to use the default config) and tried to focus on DBD when click to run, but when im focusing on dbd screen it works differently than i previously said: mouse not moves automatically and blood point counter still counting (when i remove the focus from dbd screen, mouse start to move)

**Comment by IIInitiationnn** [comment]
Would you be able to post the corresponding logs (located in the `logs` folder)?

**Comment by mateusmcordeiro** [comment]
https://pastebin.com/xwwsWtTg
https://pastebin.com/nSD81b5c

**Comment by IIInitiationnn** [comment]
This is really bizarre, it seems like it's detecting everything okay which means nothing is blocking your game, and nothing should be theoretically preventing your mouse from selecting stuff. I'm really not sure how to resolve this.

If you have multiple monitors, maybe you can try ensure your game is on your primary monitor and your Blood Emporium is on the other. You could also try being focused in the game, then using the hotkey (default Ctrl + Alt + 9, both to run and stop the program) and seeing if that works.

**Comment by mateusmcordeiro** [comment]
Im doing exacly this, i have two monitors and i use to put bloodemporium on the second one. A good information i forgot to say previously was about the hotkey, for me it only works if im focusing bloodemporium, on dbd screen is not detected.

**Comment by IIInitiationnn** [comment]
Seems like your game being focused is preventing some interactions with the OS from being executed: when your game is focused, it doesn't move the mouse, your mouse doesn't click, the hotkey doesn't register; when your game is not focused, it can move but it doesn't click in the game, and your hotkeys work.

I know you mentioned you modified some configuration files to change fullscreen behaviour etc. - is there anything else that you could have possibly changed from your installation that prevents this from working? Would it be possible to validate your installation?

**Comment by mateusmcordeiro** [comment]
I dont think so. My motivation to change this config file i said was trying to fix bloodemporium. Before that, i tried multiple times without changing anything on game files. So i read on FAQ and saw that it only works if game is on Fullscreen mode, so i supposed my game was on windowed fullscreen (not really fullscreen).

even knowing that, im going to reset my game config and try again without it. (i'll keep in touch)

Just for knowledge, to set windowed fullscreen to real fullscreen i followed this tutorial:
https://steamcommunity.com/sharedfiles/filedetails/?id=2287680083

**Comment by IIInitiationnn** [comment]
In regards to the fullscreen remark in the FAQ, it is only there to note (for v0.3.2 and older) that having the game in a window that does not span the entire screen will not allow the program to work.
If you have any experience with Python, testing (or otherwise verifying) if your system specs are compatible with pyautogui (the library used for mouse interactions) may also help determine if there are any issues. If you'd like, I can write you a short script to see if the library works on your system in general.

**Comment by mateusmcordeiro** [comment]
I`m a software engineer too, but i don't have so much xp with python. My work is uses another languages. But i can easily execute any task you ask me to do. So yes, if theres no problem with it, you can send me the instructions so ill exec them so we can see this diagnosis

**Comment by IIInitiationnn** [comment]
Hey! I may have found a potential fix. Could you try running Blood Emporium as an administrator?

**Comment by mateusmcordeiro** [comment]
wow, it worked !! Thank you so much for all support.
this is gonna help a lot of users if you put this on FAQ.

I would like to contribute to BloodEmporium. I dont know much about python, but if i see something i could help, ill certainly open a pull request. 

You can close this issue, i didnt do this because i want to see your final answer haha.

**Comment by IIInitiationnn** [comment]
Really glad it worked! Did some digging and found some stuff about games bypassing OS and not allowing pyautogui to work with the game, so this I'm really glad it works. Since there's been more than one case of this already, throwing it in the FAQ is definitely a good idea.

In terms of contributions, please don't feel obligated to do anything! Just using the app and filing bug reports if you run into any is plenty enough. If you'd like to help though, you can reach out on Discord, I'd be more than happy to help you get started, we've got a development channel in our server, though there isn't much left on the roadmap at this point in time as we approach the full v1.0.0 release.

Happy spending!
