### ISSUE TITLE
How to make this program work ?

### ISSUE THREAD

**Issue by Megalos4** [IIInitiationnn/BloodEmporium#3]
Hello, I am not sure how to make the program work. Where do I put it ? What should I do after having downloading it ? I am kind of new to this, so I would be very grateful if you could help me :)

**Comment by IIInitiationnn** [comment]
1. Download the latest version from https://github.com/IIInitiationnn/BloodEmporium/releases (under Assets, grab `Blood.Emporium.[version].zip`)
2. Unzip.
3. Run `Blood Emporium.exe`.

Let me know if you have any further difficulties :)

**Comment by Megalos4** [comment]
Thank you :)
The program launched, but when I run it, the arrow goes at the top left corner of my screen. The resolution is right. Me and a friend of mine are both trying it on our own computer, but it doesn't seem to work. Do you have any idea of what's happening ?
Thank you in advance ;)

**Comment by IIInitiationnn** [comment]
Turns out, I did not release a newer version of the program updated for the relocated bloodweb in 6.1.0 onwards. Since Dead by Daylight has been updated since then, I am not sure if my changes from several months ago are compatible with the current game version. I have uploaded a new release, feel free to try again with that version and let me know if the program is successful. If not, I will aim to release a patch in the coming days.

Please note that this program is still several updates behind in terms of content, since I discontinued developing this project several months ago, so don't expect correct perk / add-on detection for recent content.

**Comment by Organic-Code** [comment]
Does not work on my side
I don’t know how required are the game icon files, but the icon folder is mostly filled with "empty.png" instead of perks, items, addons (...) icons, and they are nowhere to be found (as png/jpg files) in my installation directory.

**Comment by IIInitiationnn** [comment]
When your icon folder is empty, the app should use the images in the assets folder, so this should not be an issue. Would you be able to provide more details on the issues you are encountering?

**Comment by Organic-Code** [comment]
As far as I can tell, just about nothing is happening when I hit "run"
I would have tried to set the icon folder to the asset folder, but I can’t find it in my installation tree
Is there any logging launch option ?

**Comment by IIInitiationnn** [comment]
Couple things to check:
- does your cursor move to the top left of your screen?
- is the "run" button replaced by a "terminate" button once clicked?
- are you running Dead by Daylight on your main monitor (if you have multiple monitors)?

**Comment by Organic-Code** [comment]
* IIRC my cursor does not move when starting (I’ll check that in a min)
* Yes, the button itself does work (afaict) and is changed to "terminate"
* I tried both monitors with the same result. If you think it might be the issue I’ll try disconnecting one so I only have the main monitor plugged in

**Comment by Organic-Code** [comment]
Switching to one monitor only does not solve the issue
the mouse cursor does not move by an inch when hitting start

**Comment by IIInitiationnn** [comment]
Couple more things to check:
- are you on Windows?
- is there a config.json file in the unzipped folder?
- check if other features such as setting your resolution in the settings work

**Comment by Organic-Code** [comment]
* I am indeed running on windows 10 pro
* Yes, a config.json file is present in the working directory
* AFAIK the settings are correct wrt screen resolution/folder

**Comment by IIInitiationnn** [comment]
Sorry for the delay in getting back to you. I have just pushed an update (v0.2.7) which will log any errors to the `logs` folder. Please update to this version and upload any relevant logs if you are still experiencing issues.

**Comment by RoinujNosde** [comment]
I'm using the release 0.2.8 and having the same problem.
Log: 
[debug-22-09-14 19-52-50.log](https://github.com/IIInitiationnn/BloodEmporium/files/9570481/debug-22-09-14.19-52-50.log)

**Comment by IIInitiationnn** [comment]
Looks like your `assets` folder is outdated. Please redownload v0.2.8, copy `config.json` from any old installation if you want to preserve your preference profiles and settings, and run it again, then let me know if you are still running into issues.

**Comment by RoinujNosde** [comment]
I downloaded it today. It is a fresh install.

**Comment by IIInitiationnn** [comment]
Are you using a custom icon pack?

**Comment by RoinujNosde** [comment]
No idea what you mean by that, so probably no.

**Comment by IIInitiationnn** [comment]
That's really odd. Would you be able to screenshot your `assets` folder?

**Comment by RoinujNosde** [comment]
![image](https://user-images.githubusercontent.com/6441328/190289495-7e31635c-c8be-4edb-b294-a6f5f396d9b1.png)
![image](https://user-images.githubusercontent.com/6441328/190289520-79a60e34-ac1e-44f9-9887-f1fc9d9bd6c0.png)

**Comment by RoinujNosde** [comment]
![image](https://user-images.githubusercontent.com/6441328/190294465-6a80181f-f637-4843-b555-86050592587d.png)

Some entries in the database have the extension appended, so the program is trying to find `.png.png` files

**Comment by IIInitiationnn** [comment]
Good catch. Can you confirm it is working if the .png suffix is removed? If so, I will push a fix shortly.

**Comment by RoinujNosde** [comment]
Yep.

**Comment by IIInitiationnn** [comment]
Fixed in [0.2.9](https://github.com/IIInitiationnn/BloodEmporium/releases/tag/v0.2.9). Thanks for your help.
