### ISSUE TITLE
WIndows defender trojan automatically removed false positive?

### ISSUE THREAD

**Issue by thatsgraphic** [IIInitiationnn/BloodEmporium#31]
![image](https://user-images.githubusercontent.com/117963545/225561651-d242bfdb-baaf-4835-8bbd-f158b1b3e05f.png)

EXE Showing up as trojan in windows defender, and automatically gets removed unless you tell it not to.

**Comment by IIInitiationnn** [comment]
A handful of other people have reported this issue too, seems like it's an issue with the library I use to compile the executable. I will aim to have this resolved in a coming update, you should be able to tell Defender to ignore the files in the meantime.

**Comment by IIInitiationnn** [comment]
@thatsgraphic 
I have just pushed an alpha version of Blood Emporium which has hopefully resolved this issue. If possible, would you be able to check if a false positive is still triggered?

**Comment by IIInitiationnn** [comment]
Most vendors are cleared for the latest version of the app, I will mark this as completed for now.
