### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by almera-vs** [IIInitiationnn/BloodEmporium#32]
Exe doesn't launch. It's still listed as a process in task manager.

I'm on windows 10

**Comment by IIInitiationnn** [comment]
Initial startup does take a while, give it a minute or two to launch.
Also double check that the path to your Blood Emporium installation doesn't contain any special unicode characters (see #5). If you're still having issues, let me know.

**Comment by almera-vs** [comment]
It definitely starts after 5-8 minutes which is a lot of time when I just want to quickly upgrade my bloodweb. So this should be addressed soon. Also I have a lot of disk usage (mostly between 30-50%) in that time. I have it unpacked on HDD disk.

**Comment by IIInitiationnn** [comment]
This is an unfortunate side effect of packing everything into a single executable (the app needs to unpack all the libraries). For future versions, I may upload an alternate compilation which contains all the libraries already unpacked (messy folder but much faster startup), or try some other solutions. In the meantime, you can try running it off your SSD.

**Comment by IIInitiationnn** [comment]
I've released a new version (v1.0.1) which should provide much faster startup. Feel free to close this issue if you feel it has been sufficiently resolved.
