### ISSUE TITLE
we need your update~

### ISSUE THREAD

**Issue by hsy991008** [IIInitiationnn/BloodEmporium#35]
we need your new vision plz

**Comment by TyokPlex** [comment]
Yeah, we need more updates, of course we know the bloodweeb update, but we still need some updates that can do the bloodweeb extremely fast and with ur app can be possible. Please update this app.

**Comment by IIInitiationnn** [comment]
I was originally planning to release an update in accordance with the release of update 6.7.0, but I was incapacitated for more than a week due to COVID and I have been extremely busy since then. It will probably be at least 3 weeks before I can release an update to incorporate the new in-game features.

**Comment by hsy991008** [comment]
God, hope you recover better, looking forward to your update.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IIInitiationnn/BloodEmporium"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月20日(星期四) 下午3:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IIInitiationnn/BloodEmporium] we need your update~ (Issue #35)





 
I was originally planning to release an update in accordance with the release of update 6.7.0, but I was incapacitated for more than a week due to COVID and I have been extremely busy since then. It will probably be at least 3 weeks before I can release an update to incorporate the new in-game features.

**Comment by IIInitiationnn** [comment]
Release v1.1.0 is out now with all new in-game features incorporated.
