### ISSUE TITLE
Terrormisu tier unset

### ISSUE THREAD

**Issue by FlamingFox911** [IIInitiationnn/BloodEmporium#38]
New event, new offering.
Need to be set to 6.10, 5.10, 4.10 and 4.10, respective to the order of default profiles.

**Comment by IIInitiationnn** [comment]
Your existing profiles will not be modified when the app is updated.
The cheapskate profiles have been updated for the event, but the Otzdarva ones won't be touched until his killer add-on tier list is updated.
