### ISSUE TITLE
Level 9 Bloodweb should use Automatic Purchase

### ISSUE THREAD

**Issue by FlamingFox911** [IIInitiationnn/BloodEmporium#39]
Slight optimization thing.

Levels 1-9 and 11 should use the Automatic Purchase, since the Entity doesn't spawn fast enough (level 11) or at all (levels 1-9). However, level 9 tries to fill in the Bloodweb one by one.

**Comment by IIInitiationnn** [comment]
I have programmed it to use automatic purchase on levels where there are a certain number of nodes. Unfortunately level 9 has too many nodes for this threshold, and it would be too much work to implement level detection, for too little gain (considering the userbase is international so their game language may be different, and thus detecting level may vary across languages). I hope you can understand why I won't be implementing this! Thank you for the suggestion nonetheless :)
