### ISSUE TITLE
Prestige

### ISSUE THREAD

**Issue by TimTomTam** [IIInitiationnn/BloodEmporium#4]
On reaching prestige the auto-selector would attempt to prestige, but didn't hold down input for long enough, and would get stuck in a loop of trying to prestige

**Comment by IIInitiationnn** [comment]
This is a known issue, and will be addressed in the next update. Thank you for taking the time to report it!

Fixed in [0.2.7](https://github.com/IIInitiationnn/BloodEmporium/releases/tag/v0.2.7).
