### ISSUE TITLE
Suggestion: Have the cheapskate option make the Entity 'eat' many branches as possible

### ISSUE THREAD

**Issue by Klaex** [IIInitiationnn/BloodEmporium#40]
Especially at higher levels, getting the Entity to eat entire branches can be really powerful to cheaply prestige.

**Comment by IIInitiationnn** [comment]
My apologies, I totally forgot to address this.
Different users will probably want different things out of their "cheapskate" mode, so having it as a profile allows user customisation. Creating a separate cheapskate mode which completely ignores what is on the bloodweb, exclusively focusing on letting entire branches get consumed, is possible but not a particularly popular request - in the case where someone might want to _not_ ignore even a single item (e.g. Bloody Party Streamers), this mode would become entirely redundant. It would be possible to combine this mode with the tier threshold to make it more useful, but I fear this complexity may cause confusion for new users.

I like to keep doors open, so if this is a feature more people would like to see, I would be happy to implement it, but for the current userbase, I do not see this as a worthwhile feature addition for the foreseeable future.
