### ISSUE TITLE
Guardian is ignored

### ISSUE THREAD

**Issue by KaosDragon** [IIInitiationnn/BloodEmporium#41]
I don't think Emporium recognizes the old icon with Steve with the bat.

**Comment by IIInitiationnn** [comment]
Just revisiting this to clarify on some information since someone in the Discord posted a related issue: are you using a custom icon pack (hence the old Babysitter icon)?

**Comment by KaosDragon** [comment]
No, I just own the Stranger Things DLC.

**Comment by IIInitiationnn** [comment]
Thanks for the info! I think I should be able to figure out a fix for this in the upcoming weeks.

**Comment by IIInitiationnn** [comment]
Fixed in [1.2.2](https://github.com/IIInitiationnn/BloodEmporium/releases/tag/v1.2.2).
