### ISSUE TITLE
Issue launching app from Serbia

### ISSUE THREAD

**Issue by Coacic** [IIInitiationnn/BloodEmporium#44]
Hi! I came across your project today and decided to try it out, sadly when I try to open it I get this error:
![image](https://github.com/IIInitiationnn/BloodEmporium/assets/36171089/c4a4643e-d3a6-446b-a580-765dabed646c)
I am on windows 10, not sure what to do or where to begin, I have not tried to compile your code, since I do not really know how to compile python project, sorry about that. Any suggestions would be appreciated.

**Comment by IIInitiationnn** [comment]
Did you install the app and run the executable? This app comes pre-compiled with an installer, you can download it at https://github.com/IIInitiationnn/BloodEmporium/releases

**Comment by Coacic** [comment]
The application has been installed through the original installer executable, I tried reinstalling it, but the same issue comes up... Any ideas what could I do to try to fix it?

**Comment by IIInitiationnn** [comment]
I'm looking into potential causes of the error. In the meantime, would you be able to try installing it at a different path? (e.g. if you installed on your SSD, install it on your hard drive instead, or in a different folder). Aside from that, no other immediate potential workarounds come to mind, so give that a shot and I'll keep you updated if I find a fix.

**Comment by IIInitiationnn** [comment]
It seems this issue might be related to your region, here's a similar problem and potential solution for someone who had issues installing Dropbox: https://www.dropboxforum.com/t5/Apps-and-Installations/Installation-fails-for-people-from-Serbia-due-to-certificates/td-p/490440

> I am from Serbia and this error is common for Python when there are government certificates (for reading government ID or driver license smart cards) installed on Windows. In order to have these on the computer you have to install them manually from the government's website, but many people / offices will have them so I suspect many people will be having problems with Dropbox until this is resolved.

> I've solved it by removing the certificates (search for "Internet options" in Start menu, go to Content > Certificates, look for everything that looks like it has to do with Serbia - I deleted one from "Personal" tab and one with name starting with MUPCA from "Intermediate" tab). Of course, do this at your own risk if you know what you're doing, I deleted them since I don't really need them. After deleting these Dropbox installed without problems.

**Comment by Coacic** [comment]
Hey thanks for the feedback! I don't even know where to start in how you found out about the certificates problem... Never in a million years would I think that could even cause an issue... Thank you for that. The program works as indented now 👍
