### ISSUE TITLE
More 7.4.0 / 7.5.0 Otz Tier Lists

### ISSUE THREAD

**Issue by FlamingFox911** [IIInitiationnn/BloodEmporium#46]
More tier lists to be considered for the Otz's Tier List.

[Offering Tierlist (7.4.0)](https://i.imgur.com/yZimdhM.jpg)
[Survivor Item Tierlist (7.5.0)](https://sp-cdn.streamlabs.com/img/03b6b1234c40a1f6d76b01415ba68836/WrFDGURrjbluMQNKIYVqmoMKoHwZ204u7F2wQwHB.png)
[Survivor Add-on Tierlist (7.5.0)](https://sp-cdn.streamlabs.com/img/03b6b1234c40a1f6d76b01415ba68836/hWy9lKczzw14jjGK3ry5qr7W1fGqWooSyDW28Zxc.png)

**Comment by IIInitiationnn** [comment]
Didn't realise these had been updated, thanks for posting!

**Comment by IIInitiationnn** [comment]
Otz tier list profiles have now been updated in [v1.2.3](https://github.com/IIInitiationnn/BloodEmporium/releases/tag/v1.2.3).
