### ISSUE TITLE
Got Banned

### ISSUE THREAD

**Issue by xNightJade** [IIInitiationnn/BloodEmporium#47]
I got banned for using this tool, don't use it as of the new updates. BH has already implemented a new bloodweb function that does just this.

**Comment by IIInitiationnn** [comment]
Hi, are you able to confirm that this app is the exact source of your ban? BHVR has been known to ban accounts with modified save files / cheats from more than 5 years ago, so I'd like to verify that you have not been banned for doing something else in the past. Additional evidence would be appreciated to validate your claims.

**Comment by xNightJade** [comment]
> Hi, are you able to confirm that this app is the exact source of your ban? BHVR has been known to ban accounts with modified save files / cheats from more than 5 years ago, so I'd like to verify that you have not been banned for doing something else in the past. Additional evidence would be appreciated to validate your claims.

I was banned back in January of 2023 around the 19th, I was sitting in a lobby by myself as Kate, it was about 9 AM for me, I saw your tool and thought "sick" so I downloaded it and ran it, moments later it kicked me to the main menu and the next couple of hours I received an email about my game ban. I can find and send the screenshots here.

**Comment by IIInitiationnn** [comment]
If you could, that would be greatly appreciated.

**Comment by Adryh22** [comment]
So...? Is it still safe to use this program or not?

**Comment by IIInitiationnn** [comment]
@OfficialModdz Just thought I'd follow up on this to get some closure, if you'd be able to provide supporting evidence I'd be very grateful.

**Comment by femboyfin** [comment]
Probably worth mentioning OP's [only repository](https://github.com/xNightJade/ToT-Hook) is a fork of a cheat with their own commits added.

**Comment by IIInitiationnn** [comment]
Seeing as how OP has still not verified the source of their ban after 6 months, I will be closing this thread. Please feel free to update this thread afterwards.
