### ISSUE TITLE
Weird python error. Can't solve particular bloodweb.

### ISSUE THREAD

**Issue by FlamingFox911** [IIInitiationnn/BloodEmporium#49]
Just a weird funky bug. Bloodweb reached this point before crashing. Rerunning does not fix it. After I manually submit it, it continues as normal.

[debug-24-06-22 07-46-56.log](https://github.com/user-attachments/files/15936357/debug-24-06-22.07-46-56.log)
![image](https://github.com/IIInitiationnn/BloodEmporium/assets/11638944/fcfb846b-d699-420c-b93d-05cf1cd4a3aa)

**Comment by IIInitiationnn** [comment]
Seems like a simple identification error, the app thought everything on the bloodweb was already claimed so it malfunctioned when it got to the step of selecting something to claim. I can add some logic to prevent it from terminating but honestly if it continues running and misidentifying everything as claimed, it will be running indefinitely anyway until manual termination.

Assuming this is a one-off error that happens as a consequence of the impossibility of achieving 100% accuracy, I will be closing this issue for now, but please feel free to reopen it if this is somehow a recurring problem. Thank you for the report nonetheless!
