### ISSUE TITLE
Program doesn't run with unicode characters in path

### ISSUE THREAD

**Issue by y383918998** [IIInitiationnn/BloodEmporium#5]
Open bloodemporium.exe directly in bandizip, and it can use after changed the all Settings. However, after the upzipped it, the same Settings cannot be used.

**Comment by IIInitiationnn** [comment]
You should unzip first before using the program. When you use a ZIP program such as Bandizip to access the files, any files created and edited are temporary cache files. In this case, the settings are saved to a configuration file `config.json` which is lost when your ZIP program is terminated. Please unzip the program, then modify your settings.

**Comment by y383918998** [comment]
You don't get what I mean, even if I unzipped it first, it's still not usable (changed icon directory, default 1920×1080 + 100% UI SCALE)

**Comment by IIInitiationnn** [comment]
Make sure you have clicked the save button at the bottom too. If that still does not work, would you be able to upload your `config.json` file?

**Comment by y383918998** [comment]
I apologize for only replying to you now, I deleted the previous zip and the unzipped folder, downloaded it again on GitHub and did the direct unzip as you said, and after setting the icon path and changing the preference profiles, I ran it and it still doesn't work as before.

On a normal working version, the mouse should continue with the AppStarting icon for a while and then automatically move to the top left corner, but when I clicked on run, it lasted less than a second and then changed back to the normal mouse icon
[config_and_MouseIcon.zip](https://github.com/IIInitiationnn/BloodEmporium/files/9855584/config_and_MouseIcon.zip)

**Comment by IIInitiationnn** [comment]
Please also send your `logs` folder.

**Comment by y383918998** [comment]
[logs.zip](https://github.com/IIInitiationnn/BloodEmporium/files/9859583/logs.zip)

**Comment by IIInitiationnn** [comment]
If you are not using a custom icon pack, try set your path back to the default path and run it again. If you are using an icon pack, I can only guess that there may be some broken files; in that case, I will need you to send the icon pack so I can have a look at any problematic files.

**Comment by y383918998** [comment]
I am playing the steam version, I have verified the integrity of the game files via steam and it does not show the missing files, I send you the icon zip, also my game files are stored on the E drive, which is an additional mechanical drive
[Icons.zip](https://github.com/IIInitiationnn/BloodEmporium/files/9862288/Icons.zip)

**Comment by IIInitiationnn** [comment]
I have just recalled a possible issue with the library used to compile the program.
Do you have any unicode characters in any of the parent directories (folders) containing the executable? For instance, Chinese or Russian characters will cause the program to fail. I'm not exactly clear on the reasons behind this, but another user did report this issue to me some time ago. If you do have any of those characters, try moving the Blood Emporium folder to another location where there are no such characters in the path.

**Comment by y383918998** [comment]
Problem solved, I have Chinese in my unzip path
