### ISSUE TITLE
Crashes when exporting bundled profiles to file

### ISSUE THREAD

**Issue by femboyfin** [IIInitiationnn/BloodEmporium#56]
If you go to Preference Profiles, and select one of the [BUNDLED] profiles, the Export Profile to File button will crash the program.

Can be worked around by clicking Save As and then exporting your saved copy of the bundled profile.

**Comment by IIInitiationnn** [comment]
Thanks for the report! Will have this fixed in the next update.

**Comment by IIInitiationnn** [comment]
Fixed in [1.2.11](https://github.com/IIInitiationnn/BloodEmporium/releases/tag/v1.2.11).
