### ISSUE TITLE
Stuck on "Downloading New Assets"

### ISSUE THREAD

**Issue by FlamingFox911** [IIInitiationnn/BloodEmporium#57]
While this can be skipped by clicking on Cancel, this modal appears on start up.

![image](https://github.com/user-attachments/assets/a014b780-3ea7-43a9-a703-e276ed1bc6b2)

**Comment by IIInitiationnn** [comment]
Thanks for the report.
How long did you wait before cancelling the update? There is a slight delay before the download begins, but if it was a significant amount of time without progress I'll have to investigate further.

**Comment by FlamingFox911** [comment]
I waited a solid 5 minutes at least. I'll test again for 30 mins and see if it changes. I'll update this comment with results.

EDIT: Okay, this time around, I didn't see the notification. Does this happen on a routine, or on startup?

**Comment by IIInitiationnn** [comment]
I disabled the update functionality after getting reports of this bug. The slight delay for me is usually less than 5 seconds, so if you've already waited even more than half a minute something isn't working.
I'll be pushing out a regular app update for bugfixes later today, it operates using the same update function. At that time, please let me know if it successfully updates (I changed the auto-update logic a little bit in the last update to make it flexible for asset updating too, and I'm concerned the actual app update functionality no longer works now too).

**Comment by FlamingFox911** [comment]
Saw the update, opened the program, I saw it download the new installer. I don't see any issues so far, so I'll close this issue. Many thanks.
