### ISSUE TITLE
NVIDIA visual filters cause unexpected behaviour

### ISSUE THREAD

**Issue by Quantum-of-Blackness** [IIInitiationnn/BloodEmporium#6]
The program tries to start the web with perks that are located on the edges. But this does not make sense because it cannot be done and therefore it ignores perks, although they have a very high priority

**Comment by IIInitiationnn** [comment]
Could you provide some clarification on what you mean by "start the web with perks that are located on the edges"?

**Comment by Quantum-of-Blackness** [comment]
https://youtu.be/VJ2gzh8Fu9A

**Comment by IIInitiationnn** [comment]
Would you be able to send me the logs corresponding to this?

**Comment by Quantum-of-Blackness** [comment]
[debug-22-11-13 15-20-10.log](https://github.com/IIInitiationnn/BloodEmporium/files/9997374/debug-22-11-13.15-20-10.log)
[debug-22-11-13 15-17-46.log](https://github.com/IIInitiationnn/BloodEmporium/files/9997375/debug-22-11-13.15-17-46.log)
Something from this

**Comment by Quantum-of-Blackness** [comment]
https://youtu.be/6mFHVF9f8oM
[debug-22-11-13 16-52-11.log](https://github.com/IIInitiationnn/BloodEmporium/files/9997386/debug-22-11-13.16-52-11.log)

I recorded another video with the log for the survivor. The video shows how the program tries to take the addon for the toolbox from the edge of the web. After the attempt, the program considers that it has already taken the addon and forgets about it

**Comment by IIInitiationnn** [comment]
Thanks for the information. I've done a decent amount of testing and debugging, and I have been unable to reproduce the error or find its cause. [Here](https://github.com/IIInitiationnn/BloodEmporium/releases/tag/v0.3.1) is a version of the app with more detailed logging; if you could run this version and send me a video and logs again when the error occurs, that would be really appreciated. Sorry for the trouble.

**Comment by Quantum-of-Blackness** [comment]
[debug-22-11-14 16-48-43.log](https://github.com/IIInitiationnn/BloodEmporium/files/10003536/debug-22-11-14.16-48-43.log)

**Comment by IIInitiationnn** [comment]
Only possible cause I can think of at the moment is visual colour changes, so just to confirm, you are not running the app with any visual shaders or filters on your game?

**Comment by Quantum-of-Blackness** [comment]
Oh, Nvidia Freestyle...
