### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by 188033155** [IIInitiationnn/BloodEmporium#7]
Can not started successfully.

LOG:
initialisation, merging
Traceback (most recent call last):
  File "state.py", line 114, in run
  File "mergedbase.py", line 55, in __init__
  File "mergedbase.py", line 80, in __get_valid_images
AttributeError: 'NoneType' object has no attribute 'shape'

![image](https://user-images.githubusercontent.com/29905312/201518030-7948af70-afc3-4d79-87f9-26e22b6721e0.png)

**Comment by IIInitiationnn** [comment]
Please make sure the path to `Blood Emporium.exe` does not contain any special unicode characters. See https://github.com/IIInitiationnn/BloodEmporium/issues/5

**Comment by IIInitiationnn** [comment]
Assuming your issue is fixed, I'll be marking this as resolved.
